---

- hosts: debian
  become: true
  become_user: jordi
  become_method: sudo
  tasks:
  - name: Instalar VIM
    ansible.builtin.apt:
      name: vim
      state: latest
      update_cache: yes
      force_apt_get: true
